### ISSUE TITLE
Vraag Intersection

### ISSUE THREAD

**Issue by WesselSlot** [HAN-ASD-DT/elm-assignment-WesselSlot#1]
He Daan,

Zo ver ik kon vinden online is een Intersection een vergelijking van 2 sets en de uitkomst is de waardes die in beide sets voorkomen. Dan is intersection of [1,6] [3,7] toch leeg en niet [3,6]?

Het is me wel gelukt hoor maar ik was gewoon benieuwd?
@dvberkel

**Comment by WesselSlot** [comment]
The intersection of two sets A and B is the set that contains all elements of A that also belong to B.

We find intersection in 2 steps:
STEP 1: Write down the elements of both sets:

A={ 1 , 6 }
B={ 3 , 7 }

STEP 2: Highlight elements that A and B have in common:
Since, these these two sets have nothing in common we conclude that the intersection is emty set.

**Comment by dvberkel** [comment]
Het interval `[1,6]` bestaat uit de getallen `{1, 2, 3, 4, 5, 6}`. Net zo bestaat het interval `[3,7]` uit de getallen `{3, 4, 5, 6, 7}`. De **intersectie** van twee verzameling is inderdaad de verzameling van elementen die in beide verzamelingen voorkomen. 

Inspectie levert dus dat de intersectie van de intervallen `[1,6]` en `[3,7]` gelijk is aan `{3,4,5,6}` omdat deze getallen in beide verzamelingen aanwezig zijn. Deze verzameling komt overeen met het interval `[3,6]`.

Jouw tweede commentaar interpreteert de interval notatie als verzameling notatie, maar die zijn verschillend. In mijn commentaar heb ik ze altijd onderscheiden. Hopelijk verduidelijkt dat de vraag en de antwoorden.
